language: ruby
bundler_args: --without production development
rvm:
  - 2.1.2
before_script:
  - 'cp ./.travis.database.yml ./config/database.yml'
  - 'cp ./.travis.application.yml ./config/application.yml'
  - 'mkdir -p ./tmp/cache'
script:
  - bundle exec rake db:setup
  - bundle exec rake test
